name: PR builder is just a magic

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get all the letters, words and paragraphs needed for the spell!
        uses: actions/checkout@v4
      - name: Prepare the cauldron and the wand!
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'maven'
      - name: Maven, now you do the magic! I enchant you the Bash way!
        run: |
          mvn install
          mvn -Prun-its verify -DskipTests
        env:
          MAVEN_ARGS: --batch-mode --no-transfer-progress --errors
